// Seed used by DEMO MODE only. Mirrors supabase/migrations/..._seed.sql so the
// prototype behaves exactly like the real backend.

export const DOCUMENT_TYPES = [
  { id: 'current_tax_sheet', category: 'base', sort_order: 10, label_en: 'Current tax sheet', label_de: 'Aktuelles Steuerformular', label_fr: "Feuille d'impôt actuelle", label_it: "Foglio d'imposta attuale", help_en: 'The form/letter you received from the tax authority for this tax year.' },
  { id: 'last_tax_return', category: 'base', sort_order: 20, label_en: 'Copy of your last tax return', label_de: 'Kopie der letzten Steuererklärung', label_fr: 'Copie de votre dernière déclaration d’impôt', label_it: "Copia dell'ultima dichiarazione d'imposta" },
  { id: 'last_tax_assessment', category: 'base', sort_order: 30, label_en: 'Copy of your last tax assessment', label_de: 'Kopie der letzten Steuerveranlagung', label_fr: 'Copie de votre dernière taxation', label_it: "Copia dell'ultima tassazione" },
  { id: 'salary_statement', category: 'income', sort_order: 40, label_en: 'Salary statement (employees) / income and expense statement (self-employed)', label_de: 'Lohnausweis / Einnahmen- und Ausgabenrechnung (Selbständige)', label_fr: 'Certificat de salaire / compte de résultat (indépendants)', label_it: 'Certificato di salario / conto economico (indipendenti)', help_en: 'One statement per employer for the tax year.' },
  { id: 'alimony', category: 'income', sort_order: 50, label_en: 'Alimony agreement and bank statements showing donor and recipient (incl. date of birth)', label_de: 'Unterhaltsvereinbarung und Bankbelege mit Zahler und Empfänger', label_fr: 'Convention de pension alimentaire et relevés bancaires', label_it: 'Accordo di mantenimento ed estratti bancari' },
  { id: 'childcare_costs', category: 'deductions', sort_order: 60, label_en: 'Third-party childcare costs (e.g. day care)', label_de: 'Drittbetreuungskosten (z. B. Kita)', label_fr: 'Frais de garde par des tiers (p. ex. crèche)', label_it: 'Costi di custodia di terzi (es. asilo nido)' },
  { id: 'debt_certificates', category: 'deductions', sort_order: 70, label_en: 'Debt certificates as of 31.12 (credit cards, private loans, mortgages)', label_de: 'Schuldenausweise per 31.12.', label_fr: 'Attestations de dettes au 31.12', label_it: 'Attestazioni dei debiti al 31.12', help_en: 'Leasing cannot be deducted in an individual tax return.' },
  { id: 'pillar_3a', category: 'deductions', sort_order: 80, label_en: 'Pillar 3a certificate / voluntary contributions to the pension fund (BVG)', label_de: 'Bescheinigung Säule 3a / freiwillige Einkäufe (BVG)', label_fr: 'Attestation pilier 3a / rachats LPP', label_it: 'Attestazione pilastro 3a / riscatti LPP' },
  { id: 'health_insurance', category: 'deductions', sort_order: 90, label_en: 'Health insurance policy or yearly premium statement', label_de: 'Krankenkassenpolice oder Jahresprämienbescheinigung', label_fr: 'Police d’assurance maladie ou attestation de primes', label_it: 'Polizza cassa malati o attestazione dei premi' },
  { id: 'medical_costs', category: 'deductions', sort_order: 100, label_en: 'Non-reimbursed medical costs and invoices', label_de: 'Nicht rückerstattete Krankheitskosten', label_fr: 'Frais médicaux non remboursés', label_it: 'Spese mediche non rimborsate' },
  { id: 'donations', category: 'deductions', sort_order: 110, label_en: 'Certificate for voluntary donations', label_de: 'Bescheinigung für freiwillige Zuwendungen', label_fr: 'Attestation pour dons volontaires', label_it: 'Attestazione per donazioni volontarie' },
  { id: 'support_payments', category: 'deductions', sort_order: 120, label_en: 'Bank transfers to a financially supported person (name, date of birth, address)', label_de: 'Überweisungen an eine unterstützte Person', label_fr: 'Virements à une personne soutenue', label_it: 'Bonifici a una persona sostenuta' },
  { id: 'bank_statements', category: 'assets', sort_order: 130, label_en: 'Bank, crypto and securities statements as of 31.12 (Swiss and foreign), incl. custody accounts', label_de: 'Bank-, Krypto- und Wertschriftenausweise per 31.12.', label_fr: 'Relevés bancaires, crypto et titres au 31.12', label_it: 'Estratti bancari, crypto e titoli al 31.12', help_en: 'Count each account/wallet as one unit — the number of units affects the fee.' },
  { id: 'pension_fund', category: 'assets', sort_order: 140, label_en: 'Pension fund statement and/or vested benefits policies', label_de: 'Pensionskassenausweis und/oder Freizügigkeitspolicen', label_fr: 'Certificat de caisse de pension / libre passage', label_it: 'Certificato cassa pensione / libero passaggio' },
  { id: 'inheritance_gift', category: 'assets', sort_order: 150, label_en: 'Inheritance, gift, early withdrawal or BVG payment received in the tax year', label_de: 'Erbschaft, Schenkung, Vorbezug oder BVG-Auszahlung', label_fr: 'Héritage, donation, versement anticipé ou LPP', label_it: 'Eredità, donazione, prelievo anticipato o LPP' },
  { id: 'property_tax_value', category: 'property', sort_order: 160, label_en: 'Official tax value statement of Swiss properties', label_de: 'Amtliche Steuerwertbescheinigung', label_fr: 'Estimation fiscale officielle', label_it: 'Stima fiscale ufficiale' },
  { id: 'rental_contract_zug', category: 'property', sort_order: 170, label_en: 'Tenants in Canton Zug only: copy of the rental contract', label_de: 'Nur Mieter im Kanton Zug: Kopie des Mietvertrags', label_fr: 'Locataires à Zoug uniquement : copie du bail', label_it: 'Solo inquilini nel Canton Zugo: copia del contratto' },
  { id: 'other', category: 'other', sort_order: 900, label_en: 'Other document', label_de: 'Weiteres Dokument', label_fr: 'Autre document', label_it: 'Altro documento' }
]

export const PRICING_ITEMS = [
  { code: 'base_single', kind: 'base', sort_order: 10, price: 240, unit: null, quantity_from: null, label_en: 'Single', label_fr: 'Célibataire', label_de: 'Alleinstehend', label_it: 'Celibe/nubile' },
  { code: 'base_married', kind: 'base', sort_order: 20, price: 320, unit: null, quantity_from: null, label_en: 'Married', label_fr: 'Marié', label_de: 'Verheiratet', label_it: 'Coniugato/a' },
  { code: 'property', kind: 'per_unit', sort_order: 30, price: 80, unit: 'property', quantity_from: null, label_en: 'Per property in Switzerland or abroad', label_fr: "Par immeuble en Suisse ou à l'étranger", label_de: 'Pro Liegenschaft im In- oder Ausland', label_it: "Per immobile in Svizzera o all'estero" },
  { code: 'assets_10', kind: 'tier', sort_order: 40, price: 100, unit: 'asset_unit', quantity_from: 10, label_en: 'Asset statements from 10 units (accounts, crypto, stocks, etc.)', label_fr: 'Relevés bancaires de 10 unités', label_de: 'Vermögensausweise ab 10 Einheiten', label_it: 'Estratti patrimoniali da 10 unità' },
  { code: 'assets_20', kind: 'tier', sort_order: 50, price: 200, unit: 'asset_unit', quantity_from: 20, label_en: 'Asset statements from 20 units (accounts, crypto, stocks, etc.)', label_fr: 'Relevés bancaires de 20 unités', label_de: 'Vermögensausweise ab 20 Einheiten', label_it: 'Estratti patrimoniali da 20 unità' },
  { code: 'self_employed', kind: 'surcharge', sort_order: 60, price: 80, unit: null, quantity_from: null, label_en: 'Self-employed', label_fr: 'Travailleur indépendant', label_de: 'Selbständigerwerbend', label_it: 'Lavoratore indipendente' },
  { code: 'shareholding', kind: 'per_unit', sort_order: 70, price: 40, unit: 'shareholding', quantity_from: null, label_en: 'Per qualifying shareholding in a company', label_fr: 'Par participation qualifiée dans des sociétés', label_de: 'Pro qualifizierte Beteiligung', label_it: 'Per partecipazione qualificata' },
  { code: 'postal_delivery', kind: 'surcharge', sort_order: 80, price: 20, unit: null, quantity_from: null, label_en: 'Tax return sent by post', label_fr: 'Déclaration envoyée par courrier', label_de: 'Steuererklärung per Post', label_it: 'Dichiarazione inviata per posta' },
  { code: 'express', kind: 'surcharge', sort_order: 90, price: 150, unit: null, quantity_from: null, label_en: 'Express tax return', label_fr: 'Déclaration express', label_de: 'Express-Steuererklärung', label_it: 'Dichiarazione express' },
  { code: 'svc_retirement', kind: 'service', sort_order: 200, price: 0, label_en: 'Retirement planning', label_fr: 'Planification de la retraite', label_de: 'Pensionsplanung', label_it: 'Pianificazione pensionistica' },
  { code: 'svc_financial', kind: 'service', sort_order: 210, price: 0, label_en: 'Financial planning', label_fr: 'Planification financière', label_de: 'Finanzplanung', label_it: 'Pianificazione finanziaria' },
  { code: 'svc_insurance', kind: 'service', sort_order: 220, price: 0, label_en: 'Optimisation of insurances', label_fr: 'Optimisation des assurances', label_de: 'Versicherungsoptimierung', label_it: 'Ottimizzazione delle assicurazioni' },
  { code: 'svc_trading', kind: 'service', sort_order: 230, price: 0, label_en: 'Trading', label_fr: 'Trading', label_de: 'Trading', label_it: 'Trading' },
  { code: 'svc_abroad_re', kind: 'service', sort_order: 240, price: 0, label_en: 'Real estate investment abroad', label_fr: "Investissement immobilier à l'étranger", label_de: 'Immobilieninvestitionen im Ausland', label_it: "Investimenti immobiliari all'estero" },
  { code: 'svc_tax_advice', kind: 'service', sort_order: 250, price: 0, label_en: 'Tax advice', label_fr: 'Conseil fiscal', label_de: 'Steuerberatung', label_it: 'Consulenza fiscale' },
  { code: 'svc_investments', kind: 'service', sort_order: 260, price: 0, label_en: 'Investments', label_fr: 'Investissements', label_de: 'Anlagen', label_it: 'Investimenti' },
  { code: 'svc_brokerage', kind: 'service', sort_order: 270, price: 0, label_en: 'Real estate brokerage', label_fr: 'Courtage immobilier', label_de: 'Immobilienvermittlung', label_it: 'Intermediazione immobiliare' }
].map((item, index) => ({ id: `price-${index}`, app_id: 'hornung_crm', active: true, ...item }))
